install.packages("ggplot2", dependencies=TRUE)
install.packages("plyr")
install. packages("ggthemes")
install.packages("reshape2")
library("ggplot2")
library("plyr")
library("ggpthemes")
library("reshape2")
head(iris)

myplot<- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))
summary(myplot)
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))+
  geom_point()  
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(size=3)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(size=3)
ggplot (data = d2, aes (x= carat, y = price, color = color)) + geom_point()      
library(MASS)
ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot()
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_wrap ( ~ Species) 
library(MASS)
library(RColorBrewer)
h <-ggplot(faithful, aes(x =waiting))
h + geom_histogram(binwidth = 30)
h <-ggplot(faithful, aes(x =waiting))
h + geom_histogram(binwidth = 8, fill = "steelblue", color = "black")
ggplot(iris, aes(Species, Sepal.Length)) + geom_bar(stat = "identity")
ggplot(df, aes(Species, value, fill = variable)) + geom_bar(stat = "identity", position ="dodge", color="black")
ggplot(d2, aes (clarity, value, fill = variable)) + geom_bar(stat = "count", color = "quality") + geom_point()
ggplot(d2, aes(clarity, value, fill = cut)) + geom_bar(stat = "count", position="dodge", color="black")
d2 <- diamonds[sample(1:dim(diamonds)[1], 1000), ]
ggplot(d2, aes(clarity, value, fill = cut)) + geom_bar(position="dodge")
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3) + geom_smooth(method = "lm")+ facet_grid(˜ Species)

myplot<- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))
summary(myplot)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3) + geom_smooth(method = "lm")+ facet_grid(˜ Species)